packages:
  - playground/*
  - docs
  - packages/*
  - examples/*

catalog:
  '@types/node': ^22.13.4
  pinia: ^3.0.1
  typescript: ^5.7.3
  unbuild: ^3.3.1
  vite: 6.1.0
  '@vitejs/plugin-vue': ^5.2.2
  '@vitejs/plugin-react': ^4.4.1
  '@vitejs/plugin-react-swc': ^3.8.0
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.0.5
  '@vitest/coverage-v8': ^3.0.5
  vue: ^3.5.13
  vue-tsc: 2.2.10
  '@vue/tsconfig': ^0.7.0
  react: ^18.3.1
  react-dom: ^18.3.1
  '@types/react': ^18.3.24
  '@types/react-dom': ^18.3.7
  eslint: ^9.20.1
  '@eslint/js': ^9.22.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.19
  typescript-eslint: ^8.26.1
  globals: ^16.0.0

ignoredBuiltDependencies:
  - '@monorepo-setup/pkg-utils'

onlyBuiltDependencies:
  - '@monorepo-setup/pkg-utils'
  - '@swc/core'
  - esbuild
