packages:
  - playground/*
  - docs
  - packages/*
  - examples/*
catalog:
  '@antfu/eslint-config': ^4.2.1
  '@antfu/ni': ^23.3.1
  '@antfu/utils': ^9.0.0
  '@iconify-json/svg-spinners': ^1.2.2
  '@shikijs/vitepress-twoslash': ^2.3.2
  '@types/node': ^22.13.4
  '@unocss/reset': ^65.5.0
  '@vueuse/core': ^12.7.0
  bumpp: ^10.0.3
  eslint: ^9.20.1
  floating-vue: ^5.2.2
  lint-staged: ^15.4.3
  pinia: ^3.0.1
  pnpm: ^10.4.0
  simple-git-hooks: ^2.11.1
  tsx: ^4.19.2
  typescript: ^5.7.3
  unbuild: ^3.3.1
  unocss: ^65.5.0
  unplugin-vue-components: ^28.1.0
  vite: ^6.1.0
  vite-tsconfig-paths: ^5.1.4
  vitepress: ^2.0.0-alpha.2
  vitepress-plugin-group-icons: ^1.3.5
  vitest: ^3.0.5
  vue: ^3.5.13
  vue-tsc: ^2.2.10
  '@vitejs/plugin-vue': ^5.2.2
  '@vue/tsconfig': ^0.7.0
  react: ^19.1.0
  react-dom: ^19.1.0
  '@types/react': ^19.0.10
  '@types/react-dom': ^19.0.4
  '@eslint/js': ^9.22.0
  '@vitejs/plugin-react-swc': ^3.8.0
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.19
  globals: ^16.0.0
  typescript-eslint: ^8.26.1
