export { default as EditorPart } from './EditorPart'
export { default as PanelPart } from './PanelPart'
export { default as SidebarPart } from './SidebarPart'
export { default as TitlebarPart } from './TitlebarPart'
export { default as ActivitybarPart } from './ActivitybarPart'
export { default as AuxiliarybarPart } from './AuxiliarybarPart'
export { default as FooterbarPart } from './FooterbarPart'